language: node_js
node_js:
  - "8"
sudo: true
dist: trusty

install:
  - pip install -r requirements.txt
script:
  - ng build -bh "https://klaw.azurewebsites.net/"
before_deploy:
  - cd build
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true