language: python
python: 3.4
install:
  - pip install -r requirements.txt
script:
  - python hello.py
 deploy:
  provider: azure_web_apps
  username: AZURE_WA_USERNAME
  password: AZURE_WA_PASSWORD
  site: AZURE_WA_SITE


